### ISSUE TITLE
PrincipalPermissionAttribute issue

### ISSUE THREAD

**Issue by MulixBF** [T4MVC/T4MVC#43]
Hello.

In our project we have a controller with PrincipalPermissionAttribute on it. In our main menu we have an ActionLink to one of the methods of this controller. And when we use autogenerated T4MVC class we have a runtime exception of type TypeInitializationException with inner SecurityException with "Request for principal permission failed" message. It looks like autogenerated class is instantiating a controller when we need only a link to one of it's methods. Is it the case or are we missing something?

**Comment by davidebbo** [comment]
T4MVC creates a derived class that it needs to instantiate, and it overrides all the relevant methods. So while node of your actual controller methods get called, the controller class does get instantiated (since it's the base). Not sure if there is an easy way around that, as it's a fundamental part of how T4MVC works.
