### ISSUE TITLE
Unspecified error (Exception from HRESULT: 0X80004005 (E_FAIL)) 

### ISSUE THREAD

**Issue by dotnetdeveloper786** [T4MVC/T4MVC#82]
When i create web application in 4.5 framework it gives me this error in Visual Studio 2015

Unspecified error (Exception from HRESULT: 0X80004005 (E_FAIL))

**Comment by davidebbo** [comment]
That doesn't sound related to T4MVC.

**Comment by worthy7** [comment]
EDIT: Nevermind, I couldn't reproduce this again easily. Permission errors? This never happens when running the tool manually.

Hi there, I think I can shed some new light on this (I have been getting this error for a long time, but just ignored it).

The problem is, that when compiling for debugging mode, the T4MVC code tries to delete any current T4MVC.cs file in the project - before recreating it. BUT during debugging the files are all locked for "read only" access, which means the T4 template cannot delete the file.
I confirmed this by just switching to "Release" which worked fine. And reconfirmed by switching back to debugging, compiling, and getting the error again.

This is what pointed me in that direction:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/d426d3e5-b239-4a38-a6ad-b6dcbb451724/envdteprojectitemdelete-always-throws-when-debugging?forum=vsx&prof=required

I'm not sure what the solution is though, getting T4 to run before it locks the files somehow?
